### ISSUE TITLE
rust初学者，关于包、crate和模块的问题求解答

### ISSUE THREAD

**Issue by NotionNest** [rust-boom/rust-boom#2]
你好，我是rust 初学者，现在有个问题不知是否可以在这里请教下：
在两个crate 中，如何互相引用各自的mod，例如在lib.rs 中定义的mod 想要在main.rs 中使用。
尝试过使用`crate::` , 但是这个根只负责main.rs下，也尝试过将模块拆分成文件，但应该不是我想要的结果 ⬇️
``` 
// main.rs
mod foront_of_house;
fn main() {
}
// foront_of_house.rs
pub mod serving {
  ...
}
```
希望能得到解答，谢谢～

**Comment by Lydanne** [comment]
crate:: 换成你的包名试试，我写了一个例子就在这个仓库里

**Comment by NotionNest** [comment]
OK，问题解决了，谢谢学长^_^

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: WumaCoder ***@***.***>
发送时间: Thursday, August 11, 2022 10:04:44 AM
收件人: WumaCoder/rust-boom ***@***.***>
抄送: aiden ***@***.***>; Author ***@***.***>
主题: Re: [WumaCoder/rust-boom] rust初学者，关于包、crate和模块的问题求解答 (Issue #2)


crate:: 换成你的包名试试，我写了一个例子就在这个仓库里

―
