### ISSUE TITLE
tui-rs已经不再更新，建议替换为ratatui

### ISSUE THREAD

**Issue by plokid** [rust-boom/rust-boom#4]
https://github.com/ratatui-org/ratatui

**Comment by Lydanne** [comment]
感谢你的反馈，我尽快处理一下

**Comment by plokid** [comment]
另外druid开发也终止了

**Comment by Lydanne** [comment]
> https://github.com/ratatui-org/ratatui

https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci8xY2YxM2MzNjhjZjRlYjMxNWQ2ZTRkMzQxMDc0MjRiNTIyNzRiZDAxL2MvYjdiZGNiMmU1ZmFjOTI3ODFlMWU5MTYzNTUyMGFjODY1MjZlNGIwMz91cmw9Z2l0JTQwZ2l0aHViLmNvbSUzQXJ1c3QtYm9vbSUyRnJ1c3QtYm9vbS5naXQ%3D

**Comment by Lydanne** [comment]
> 另外druid开发也终止了

https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci8xY2YxM2MzNjhjZjRlYjMxNWQ2ZTRkMzQxMDc0MjRiNTIyNzRiZDAxL2MvNDQ1MmQxNGIyNmZiZjdiZmMwZGQzNjJiNmNhMWU2ZDY3YmJiYzYwMD91cmw9Z2l0JTQwZ2l0aHViLmNvbSUzQXJ1c3QtYm9vbSUyRnJ1c3QtYm9vbS5naXQ%3D
