### ISSUE TITLE
《一文让你在 rust 实现多态》文章有问题

### ISSUE THREAD

**Issue by OCNYang** [rust-boom/rust-boom#5]
这段代码：
[](https://github.com/rust-boom/rust-boom/blob/master/docs/s3_dyn_trait/readme.md?plain=1#L120-L128)

结构 Render.elements 只会接收“实现了 IElement” 的实例，
也就是：

```rust
    let mut  render = Render {
        elements: Vec::new(), // 这里是空数组，不放数据是没有意义的；放数据的话只允许存放实现了 IElement 的实例；
    };
    render.elements.push(Box::new(AElement{})); // 错误，这里是不能的
```

也就是说 Render 和 DivElement、AElement 是毫不相干的；
那么这里所谓的多态是不成立的，也是没有意义的。

我是 Rust 初学者，不知理解的对不对？
但测试示例代码，是跑不起来的。

**Comment by Lydanne** [comment]
> 这段代码：
> 
> 结构 Render.elements 只会接收“实现了 IElement” 的实例， 也就是：
> 
> ```rust
>     let mut  render = Render {
>         elements: Vec::new(), // 这里是空数组，不放数据是没有意义的；放数据的话只允许存放实现了 IElement 的实例；
>     };
>     render.elements.push(Box::new(AElement{})); // 错误，这里是不能的
> ```
> 
> 也就是说 Render 和 DivElement、AElement 是毫不相干的; 那么这里所谓的多态是不成立的，也是没有意义的。
> 
> 我是 Rust 初学者，不知理解的对不对？ 但测试示例代码，是跑不起来的。

什么错误
